### ISSUE TITLE
Set up test Ruuter instance to pass requests to Turvis

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Turvis#7]
AS A Product Owner
I WANT test instances of Ruuter and Turvis to be set up and Ruuter passing all of its incoming requests to Turvis
SO THAT I would have a test playground to validate the current state of Turvis and its developments

### Acceptance Criteria

- [ ] Ruuter's requests passing functionality based on https://github.com/buerokratt/Ruuter/issues/9
- [ ] Use the latest version of [Ruuter](https://github.com/buerokratt/Ruuter)
- [ ] Use the latest version of [Turvis](https://github.com/buerokratt/Turvis)

#### Docker Compose

- [ ] Launch `turvis-test` on port `8500`
- [ ] Launch `turvis-ruuter-test` on port `8505`

**Comment by turnerrainer** [comment]
Blocked as Ruuter does not pass all the incoming parameters to a third-party endpoint (Turvis).

**Comment by hmargus** [comment]
Here we have open questions:

1) When ruuter is configured to have external forwarding, the configuration states what is the external endpoint and whether the request is forwarded with GET or POST method. This hides the context of how the initial request was initiated. e.g. when client does a GET request to ruuter and ruuter forwards the request via POST to external endpoint then external endpoint does not know if it was originally GET or POST request
2) When ruuter knows how to use path variables, such as /user/:id/report then the context is not recognizable in external endpoint, e.g. when ruuter does the mapping and replaces /user/431/report then external endpoint does not have the knowledge of what 431 means as the only piece of information is the path string
3) query parameters are lost when spring's WebClient is used for forwarding the request.
